
-- Only insert sample data if tables are empty
INSERT OR IGNORE INTO images (
  uuid, filename, original_filename, storage_path, title, caption, 
  mime_type, width, height, size_bytes, uploaded_by, privacy, view_count,
  is_ai_generated, generation_prompt, generation_model, generation_provider,
  created_at, updated_at
) VALUES 
('demo-img-001', 'landscape1.jpg', 'mountain_sunset.jpg', '/storage/landscape1.jpg', 
 'Mountain Sunset', 'Beautiful sunset over mountain peaks', 'image/jpeg', 1200, 800, 245760, 'demo-user-1', 'public', 15, 0,
 NULL, NULL, NULL, datetime('now', '-3 days'), datetime('now', '-3 days')),
 
('demo-img-002', 'forest2.jpg', 'forest_path.jpg', '/storage/forest2.jpg',
 'Forest Path', 'A winding path through a lush forest', 'image/jpeg', 1024, 768, 198400, 'demo-user-2', 'public', 23, 0,
 NULL, NULL, NULL, datetime('now', '-2 days'), datetime('now', '-2 days')),
 
('demo-img-003', 'ocean3.jpg', 'ocean_waves.jpg', '/storage/ocean3.jpg',
 'Ocean Waves', 'Powerful waves crashing against rocks', 'image/jpeg', 1600, 900, 312500, 'demo-user-1', 'public', 8, 0,
 NULL, NULL, NULL, datetime('now', '-1 day'), datetime('now', '-1 day')),
 
('demo-img-004', 'ai_art1.jpg', 'ai_generated_art.jpg', '/storage/ai_art1.jpg',
 'Abstract AI Art', 'A colorful abstract composition generated by AI', 'image/jpeg', 1024, 1024, 204800, 'demo-user-2', 'public', 31, 1,
 'Create a vibrant abstract artwork with flowing colors and geometric patterns', 'DALL-E 3', 'OpenAI', datetime('now'), datetime('now'));

-- Insert sample albums
INSERT OR IGNORE INTO albums (
  uuid, name, description, created_by, privacy, created_at, updated_at
) VALUES 
('demo-album-001', 'Nature Collection', 'Beautiful landscapes and nature photography', 'demo-user-1', 'public', 
 datetime('now', '-2 days'), datetime('now', '-2 days')),
 
('demo-album-002', 'AI Generated Art', 'Collection of AI-generated artistic images', 'demo-user-2', 'public',
 datetime('now', '-1 day'), datetime('now', '-1 day'));

-- Insert sample tags
INSERT OR IGNORE INTO tags (name, color, created_at) VALUES 
('demo-landscape', '#10B981', datetime('now', '-3 days')),
('demo-nature', '#059669', datetime('now', '-3 days')),
('demo-sunset', '#F59E0B', datetime('now', '-3 days')),
('demo-forest', '#065F46', datetime('now', '-2 days')),
('demo-ocean', '#0891B2', datetime('now', '-1 day')),
('demo-ai-generated', '#8B5CF6', datetime('now')),
('demo-abstract', '#7C3AED', datetime('now'));
